/*
 * Vetstoria Booking API
 *
 * Booking API for 3rd party consumption
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AvailabilityRequestDto struct {
	LocationId int32 `json:"locationId"`
	// Array of schedule ids to get availabilities.
	ScheduleIds []int32 `json:"scheduleIds"`
	Period PeriodDto `json:"period"`
	Appointments []AvailabilityRequestAppointmentDto `json:"appointments"`
}
