/*
 * Vetstoria Booking API
 *
 * Booking API for 3rd party consumption
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type BookingDto struct {
	LocationId int32 `json:"locationId"`
	ScheduleId int32 `json:"scheduleId"`
	Slot time.Time `json:"slot"`
	Client ClientDto `json:"client"`
	Appointments []AppointmentDto `json:"appointments"`
	BookingId string `json:"BookingId"`
}
