/*
 * Vetstoria Booking API
 *
 * Booking API for 3rd party consumption
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BookingRequestAppointmentDto struct {
	Index int32 `json:"index"`
	AppointmentTypeId int32 `json:"appointmentTypeId"`
	SpeciesId int32 `json:"speciesId"`
	PatientName string `json:"patientName"`
	Notes string `json:"notes"`
}
