/*
 * Vetstoria Booking API
 *
 * Booking API for 3rd party consumption
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"time"
)

type InlineResponse200 struct {
	Token  string    `json:"token,omitempty"`
	Expiry time.Time `json:"expiry,omitempty"`
}

func (m *InlineResponse200) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

func (m InlineResponse200) MarshalBinary() ([]byte, error) {
	return json.Marshal(m)
}
