/*
 * Vetstoria Booking API
 *
 * Booking API for 3rd party consumption
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AppointmentTypeDto struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
