/*
 * Vetstoria Booking API
 *
 * Booking API for 3rd party consumption
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject struct {
	Key string `json:"key,omitempty"`
	Secret string `json:"secret,omitempty"`
}
