/*
 * Vetstoria Booking API
 *
 * Booking API for 3rd party consumption
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ClientDto struct {
	ClientId string `json:"clientId,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	Lastname string `json:"lastname,omitempty"`
	Email string `json:"email"`
	Phone string `json:"phone"`
}
